### ISSUE TITLE
No logo or service text in view?

### ISSUE THREAD

**Issue by theflightrs** [backdrop-contrib/socialfield#29] opened 2024-10-25 03:41 UTC
I added a view as a profile tab `user/%/extras` but it only returns thin strips with the color of each service. 

This is all i see for Instagram and Youtube:
![2024-10-25 04 31 53 www jumphub eu ec102efdeb43](https://github.com/user-attachments/assets/5414fed2-1c59-4569-8a94-a3ad0d5ddb6b)

My mouse gets a link on hover (status bar), but no visible text, link or logo.  
I examined it with devools but there's no fix with `width:` `display: ` `size:` etc.

The view:

![2024-10-25 04 35 53 www jumphub eu 9ca15020e649](https://github.com/user-attachments/assets/8e8e8e15-385a-45cc-ae9d-f9f1fadbbded)

Is this a view issue or is the module yet to be refurbished?

---------------------

### (Other side encounters):

1 - Drag sorting in `Profile -> Manage Fields -> Social Link -> Edit` doesn't save, even when changing the weight boxes.
_(I think it would be nicer if "Show row weights" would be hidden from the frontend)_ 

2 -  Https is standard for most of these sites these days i believe;
`$current_element['url']['#value'] = 'http://'`  to
`$current_element['url']['#value'] = 'https://'`

3 - _Pattern_ `[field_social_links-service]` _returns the name in lowercase. I tried to list the links textually._

**Comment by laryn** [comment] 2024-10-25 04:28
@theflightRS I'm not currently using this module, but I'd recommend trying the dev version and reporting back if things are working better. It may be time for a new release if so. There have been a bunch of commits to dev that aren't in the latest official release.

**Comment by theflightrs** [comment] 2024-10-25 15:42
@laryn Thanks, i was using the 2016 version. This is from the dev one `1.x-1.x`, with just a slight variation...: 

![2024-10-25 16 42 58 www jumphub eu 6c2a70c661ff](https://github.com/user-attachments/assets/af6991db-c57b-442d-af54-35c5848a83fa)
_(Comma separator? None here:)_

![2024-10-25 17 39 12 www jumphub eu 3dc81fa90562](https://github.com/user-attachments/assets/32225f93-157d-4261-9099-8890fb438917)

For replacement patterns i tested these 4 tokens:

```
[field_extras_social_links] 
[field_extras_social_links-service] 
[field_extras_social_links-url] 
[field_extras_social_links-weight]
```

![2024-10-25 16 54 00 www jumphub eu a7182795700d](https://github.com/user-attachments/assets/18aa0d4d-123e-4363-a18c-e7534ad3c2f6)

Not too tragic, though. It's just social links. I can wait.

I don't even know how the colored output would look like. I'd be fine with stylistically having the service's logo and/or the bold service name above the link - which isn't linked, but the name is in lowercase.

(Lastly, drag reordering saves in the frontend now, but not in the backend).

**Comment by jenlampton** [comment] 2024-12-10 22:12
I think this is a duplicate of https://github.com/backdrop-contrib/socialfield/issues/18, since it sounds like you aren't already using a module that provides the icons. 

I agree, this module should provide them! I'll work in adding some in that issue.

**Closed as completed by jenlampton** 2024-12-10 22:12 UTC
Labels: duplicate
